Update CIS 1.1.0 > 1.11 exclude user details from dimension. closes #28 closes #29
turbot/steampipe-mod-oci-compliance pull request #33
Opened 2021-10-18 13:03 UTC by misraved

### Checklist
- [ ] Issue(s) linked

2022-08-29 17:27 UTC, cbruno10 requested changes
@misraved Please see comments, thanks!

2022-08-29 17:27 UTC, cbruno10 commented on query/identity/identity_administrator_user_with_no_api_key.sql
> -  a.name,
Did you test this query? I believe it will fail due to a trailing comma above.

2022-08-29 17:27 UTC, cbruno10 commented on query/core/core_network_security_list_restrict_ingress_rdp_all.sql
>    coalesce(c.title, 'root') as title
I'm confused on what our standard set of additional dimensions are across queries in this mod. Here we have region, compartment_id, and a compartment name as `title`, while in others we just have region and compartment_id, and in other queries, like https://github.com/turbot/steampipe-mod-oci-compliance/blob/a43e4dff6b243d26ecb020312c56f1317b5e1a9d/query/kms/kms_cmk_rotation_365.sql#L35, we have region and the compartment name as `compartment`.

2023-04-18 07:10 UTC, misraved commented
The changes have been addressed in https://github.com/turbot/steampipe-mod-oci-compliance/pull/59

2023-04-18 07:10 UTC, closed without merging